[project]
name = "download-videos"
version = "0.1.0"
description = ""
authors = [
    {name = "senrajudson",email = "judsonnascimento.filho@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi (>=0.135.1,<0.136.0)",
    "uvicorn (>=0.41.0,<0.42.0)",
    "yt-dlp (>=2026.3.3,<2027.0.0)",
    "ffmpeg (>=1.4,<2.0)",
    "pandas (>=3.0.1,<4.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode=false
